name: output github context(3rd Module)

on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        # Corrected line: The toJson function is now inside the GitHub Actions expression.
        run: 'echo "GitHub Context: ${{ toJson(github) }}"'
        # Outputs the GitHub context to the console  toJSON GitHub funkcija