name: output github context(3rd Module)

on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        # Corrected line: The toJson function is now inside the GitHub Actions expression.
        # run: 'echo "GitHub Context: ${{ toJson(github) }}"' # sitas failna turi echo atskita kaip apacioje
        run: |
            echo 'GitHub Context:'
            echo '${{ toJSON(github) }}' # nenaudoti double quotes nes json turi savyje double ir tada failina pipelinas
        # Outputs the GitHub context to the console  toJSON GitHub funkcija