name: Section5- Deploy website
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Section5/react/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: Section5/react
        run: npm ci
      - name: Lint code
        working-directory: Section5/react
        run: npm run lint
      - name: Test code
        working-directory: Section5/react
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: Section5/react
        run: npm ci
      - name: Build website
        working-directory: Section5/react
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-dist-files
          path: |
            Section5/react/dist  # sita vieta turi sutapti kur build komanda storina ta ir nukreipiam
            Section5/react/package.json  # cia sutampa su failu source kodo failu ir jis uploadinamas
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
